swagger: '2.0'
info:
  version: 1.0.0
  title: Node Seed Project
  description: |
    Seed Project

    Produção: nome-do-projeto.api.com

    Homologação: nome-do-projeto.homolog-interna.com

host: nome-do-projeto.homolog-internacom
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /user:
    get:
      summary: Lista todos as configurações.
      responses:
        200:
          description: Array com todas as configurações
          schema:
            type: array
            items:
              $ref: '#/definitions/setting'


definitions:
  settingTypes:
    type: string
    description: Tipo do valor de configuração
    enum: &settingTypes
      - BOOLEAN
      - NUMBER
      - FLOAT
      - STRING
      - OBJECT
  setting:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/settingTypes'
      createdAt:
        type: number
      updatedAt:
        type: number